export default {
	// 设备检测相关
	GET_DEVICE_INFO: 'GET_DEVICE_INFO',
	RECEIVE_DEVICE_INFO: 'RECEIVE_DEVICE_INFO',
	GET_MAC_ADDRESS: 'GET_MAC_ADDRESS',
	RECEIVE_MAC_ADDRESS: 'RECEIVE_MAC_ADDRESS',

	// 自动更新
	CHECK_FOR_UPDATES: 'CHECK_FOR_UPDATES', //检查是否有更新
	UPDATE_AVAILABLE_RESULT: 'UPDATE_AVAILABLE_RESULT', //检查更新的结果
	DOWN_LOAD_PROGRESS: 'DOWN_LOAD_PROGRESS', //下载进度
	START_UPDATE: 'START_UPDATE', //开始更新
	STOP_UPDATE: 'STOP_UPDATE', //停止更新

	// 窗口相关
	MIN_WINDOW: 'MIN_WINDOW',
	CLOSE_WINDOW: 'CLOSE_WINDOW',
	MAX_WINDOW: 'MAX_WINDOW',

	OPEN_WINDOW_LIVE: 'OPEN_WINDOW_LIVE',
	MIN_WINDOW_LIVE: 'MIN_WINDOW_LIVE',
	CLOSE_WINDOW_LIVE: 'CLOSE_WINDOW_LIVE',
	MAX_WINDOW_LIVE: 'MAX_WINDOW_LIVE',

	OPEN_WINDOW_CREATE: 'OPEN_WINDOW_CREATE',
	MAX_WINDOW_CREATE: 'MAX_WINDOW_CREATE',
	MIN_WINDOW_CREATE: 'MIN_WINDOW_CREATE',
	CLOSE_WINDOW_CREATE: 'CLOSE_WINDOW_CREATE',

	// 外部协议
	OPEN_EXTERNAL: 'OPEN_EXTERNAL',

	GET_LIVE_PARAMS: 'GET_LIVE_PARAMS',
	RECEIVE_LIVE_PARAMS: 'RECEIVE_LIVE_PARAMS',

	GET_CONFIG: 'GET_CONFIG',
	RECEIVE_CONFIG: 'RECEIVE_CONFIG',

	// 录屏
	START_CAPTURE_VIDEO: 'START_CAPTURE_VIDEO',
	STOP_CAPTURE_VIDEO: 'STOP_CAPTURE_VIDEO',
	SAVE_CAPTURE_VIDEO: 'SAVE_CAPTURE_VIDEO',
	UPLOAD_CAPTURE_VIDEO_SUCCESS: 'UPLOAD_CAPTURE_VIDEO_SUCCESS',
	UPLOAD_CAPTURE_VIDEO_FAILED: 'UPLOAD_CAPTURE_VIDEO_FAILED',

	// 直播间数据
	GET_CLASSROOM: 'GET_CLASSROOM',

	// 磁盘容量
	CHECK_DISK: 'CHECK_DISK',
	CHECK_DISK_SUCCESS: 'CHECK_DISK_SUCCESS',

	// 录制视频
	CHECK_VIDEO: 'CHECK_VIDEO',
	CHECK_VIDEO_SUCCESS: 'CHECK_VIDEO_SUCCESS',

	// 视频转码与上传
	// 转码
	VIDEO_HANDLE: 'VIDEO_HANDLE',
	VIDEO_HANDLE_SUCCESS: 'VIDEO_HANDLE_SUCCESS',

	// 删除视频
	DELETE_VIDEO: 'DELETE_VIDEO'

}
