export default {
	// 自动更新
	CHECK_FOR_UPDATES: 'CHECK_FOR_UPDATES', //检查是否有更新
	UPDATE_AVAILABLE_RESULT: 'UPDATE_AVAILABLE_RESULT', //检查更新的结果
	DOWN_LOAD_PROGRESS: 'DOWN_LOAD_PROGRESS', //下载进度
	START_UPDATE: 'START_UPDATE', //开始更新
	STOP_UPDATE: 'STOP_UPDATE', //停止更新

	// 窗口相关
	MIN_WINDOW: 'MIN_WINDOW',
	CLOSE_WINDOW: 'CLOSE_WINDOW',
	MAX_WINDOW: 'MAX_WINDOW',

	OPEN_WINDOW_LIVE: 'OPEN_WINDOW_LIVE',
	MIN_WINDOW_LIVE: 'MIN_WINDOW_LIVE',
	CLOSE_WINDOW_LIVE: 'CLOSE_WINDOW_LIVE',
	MAX_WINDOW_LIVE: 'MAX_WINDOW_LIVE',

	OPEN_WINDOW_CREATE: 'OPEN_WINDOW_CREATE',
	MAX_WINDOW_CREATE: 'MAX_WINDOW_CREATE',
	MIN_WINDOW_CREATE: 'MIN_WINDOW_CREATE',
	CLOSE_WINDOW_CREATE: 'CLOSE_WINDOW_CREATE',

	// 外部协议
	OPEN_EXTERNAL: 'OPEN_EXTERNAL',

	GET_LIVE_PARAMS: 'GET_LIVE_PARAMS',
	RECEIVE_LIVE_PARAMS: 'RECEIVE_LIVE_PARAMS',

	GET_CONFIG: 'GET_CONFIG',
	RECEIVE_CONFIG: 'RECEIVE_CONFIG',

	// 备忘录相关
	SET_MEMO: 'SET_MEMO'
}
